simplyret/urls.py
from django.urls import path
from .views import main, check_calibration, upload_unique_id, create_script, check_current, upload_current, set_ret

urlpatterns = [
    path('set_ret/', set_ret, name='set_ret'),
    path('upload_current/', upload_current, name='upload_current'),
    path('check_current/', check_current, name='check_current'),
    path('create_script/', create_script, name='create_script'),
    path('upload_unique_id/', upload_unique_id, name='upload_unique_id'),
    path('check_calibration/', check_calibration, name='check_calibration'),
    path('', main, name='main'),
]

simplytechdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('simplyret/', include('simplyret.urls')),
    path('techdb/', include('techdb.urls')),
    path('', RedirectView.as_view(url='/techdb/', permanent=True))
]

techdb/urls.py
from django.urls import path, include

from .views import index, by_category, phonebook, site_view, new_site, SearchResultsView, bss_info, tn_info, shedule, \
    useful_sites, new_site_info

urlpatterns = [
    path('tn_info/', tn_info, name='tn_info'),
    path('bss_info/', bss_info, name='bss_info'),
    path('phonebook/', phonebook, name='phonebook'),
    path('useful_sites/', useful_sites, name='useful_sites'),
    path('shedule/', shedule, name='shedule'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path("site/<int:site_id>/", site_view, name="site_view"),
    path('new_info/', new_site_info, name='new_site_info'),
    path('new/', new_site, name='new'),
    path('<int:category_id>/', by_category, name='by_category'),
    path('', index, name='index'),
]

simplyret/models.py
# from django.db import models

# Create your models here.

simplyret/forms.py
from django import forms


class ConnectionForm(forms.Form):
    bs = forms.CharField(max_length=10, label='Номер сетевого элемента')
    login = forms.CharField(max_length=10, label='Имя пользователя ESC')
    password = forms.CharField(max_length=15, label='Пароль пользователя ESC')
    server = forms.ChoiceField(choices=[('ESC01', 'ESC01'), ('ESC02', 'ESC02'), ('ESC03', 'ESC03'), ('ESC04', 'ESC04'),
                                        ('ESC05', 'ESC05'), ('ESC06', 'ESC06'), ('ESC07', 'ESC07'), ('ESC08', 'ESC08'),
                                        ('ESC09', 'ESC09')], label='Сервер ESC')


class CheckingForm(forms.Form):
    bs = forms.CharField(max_length=10, label='Номер сетевого элемента')

simplyret/views.py
from django.shortcuts import render
from .forms import ConnectionForm, CheckingForm
from .simply import check_calibration_BS, upload_unique_id_BS, check_uniqueid, set_ret_on_BS
from .create_script import create_script_mos

RET_LIST_GLOBAL = []


def main(request):
    bs = ''
    form = ConnectionForm(request.POST or None)
    context = {'form': form, 'bs': bs}
    return render(request, 'simplyret/index.html', context)


def check_calibration(request):
    bs = request.POST.get("bs")
    login = request.POST.get("login")
    password = request.POST.get("password")
    server = request.POST.get("server")
    RET_list = check_calibration_BS(bs, login, password, server)
    context = {'login': login, 'password': password, 'bs': bs, 'server': server, 'RET_list': RET_list}
    return render(request, 'simplyret/check-calibration.html', context)


def upload_unique_id(request):
    bs = request.POST.get("bs")
    login = request.POST.get("login")
    password = request.POST.get("password")
    server = request.POST.get("server")
    RET_list = upload_unique_id_BS(bs, login, password, server)
    global RET_LIST_GLOBAL
    RET_LIST_GLOBAL = RET_list
    # add download file
    context = {'login': login, 'password': password, 'bs': bs, 'server': server, 'RET_list': RET_list}
    return render(request, 'simplyret/upload-unique-id.html', context)


def create_script(request):
    RET_list = RET_LIST_GLOBAL
    i = 1
    for item in RET_list:
        item.append(request.POST.get(f"tech_{i}"))
        item.append(request.POST.get(f"tilt_{i}"))
        i += 1
    bs = request.POST.get("bs")
    result = create_script_mos(bs, RET_list)
    form = ConnectionForm(request.POST or None)
    context = {'bs': bs, 'RET_list': RET_list, 'form': form, 'result': result}
    return render(request, 'simplyret/create-script.html', context)


def check_current(request):
    form = CheckingForm(request.POST or None)
    context = {'form': form}
    return render(request, 'simplyret/check-current.html', context)


def upload_current(request):
    bs = request.POST.get("bs")
    RET_list = check_uniqueid(bs)
    global RET_LIST_GLOBAL
    RET_LIST_GLOBAL = RET_list
    context = {'bs': bs, 'RET_list': RET_list}
    return render(request, 'simplyret/upload-current.html', context)


def set_ret(request):
    bs = request.POST.get("bs")
    login = request.POST.get("login")
    password = request.POST.get("password")
    server = request.POST.get("server")
    result = set_ret_on_BS(bs, login, password, server)
    context = {'login': login, 'password': password, 'bs': bs, 'server': server, 'result': result}
    return render(request, 'simplyret/set-ret.html', context)

simplyret/templates/simplyret/check-calibration.html
{% extends "layout/basic_ret.html" %}
{% block title %}
{{ bs }} проверка калибровки
{% endblock %}
{% block content %}
<main class="page-main">
	<div class="hero_container">
		<section class="search">
			<h3 class="search__title">Проверка калибровки RET на {{ bs }}</h3>
			<p class="search__disclaimer">БС: {{ bs }}</p>
			<p class="search__disclaimer">Имя пользователя: {{ login }}</p>
			<p class="search__disclaimer">Сервер: {{ server }}</p>
			{% if RET_list == "No_connection" %}
			<p class="duty__text">Сетевой элемент {{ bs }} недоступен или не существует!</p>
			{% elif RET_list == "No_auth" %}
			<p class="duty__text">Нет подключения! Проверьте имя/пароль пользователя ESC!</p>
			{% elif RET_list == "No_rets" %}
			<p class="duty__text">На сетевом элементе {{ bs }} нет прописанных RET!</p>
			{% else %}
			<table class="ret__table">
				<tr>
					<th class="ret__table-title">№</th>
					<th class="ret__table-title">RET label</th>
					<th class="ret__table-title">Sector</th>
					<th class="ret__table-title">RRU</th>
					<th class="ret__table-title">Unique ID</th>
					<th class="ret__table-title">Current El Tilt</th>
					<th class="ret__table-title">Operational State</th>
				</tr>
			    {% for ret in RET_list %}
			    {% if ret.2 == 1 %}
			    <tr>
			    	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.0 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.1 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.2 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.3 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.4 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.6 }}</td>				
			    	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.7 }}</td>
			    </tr>
			    {% elif ret.2 == 2 %}
			    <tr>
			    	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.0 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.1 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.2 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.3 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.4 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.6 }}</td>				
			    	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.7 }}</td>
			    </tr>
			    {% else %}
			    <tr class="sites__table-row">
			    	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.0 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.1 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.2 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.3 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.4 }}</td>
			    	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.6 }}</td>				
			    	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.7 }}</td>
			    </tr>
			    {% endif %}
			    {% endfor %}
		    </table>
			{% endif %}
		</section>
	</div>
</main>
{% endblock %}

simplyret/templates/simplyret/check-current.html
{% extends "layout/basic_ret.html" %}
{% block title %}
Текущая выгрузка
{% endblock %}
{% block content %}
<main class="page-main">
	<div class="hero_container">
		<section class="search">
			<h3 class="search__title">Проверка наличия текущей выгрузки</h3>
            <form action="{% url 'upload_current' %}" method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<input class="site__comments-button" type="submit" name="submit" value="Проверить" />
			</form>
		</section>
	</div>
</main>
{% endblock %}

simplyret/templates/simplyret/create-script.html
{% extends "layout/basic_ret.html" %}
{% block title %}
{{ bs }} создание скрипта
{% endblock %}
{% block content %}
<main class="page-main">
	<div class="hero_container">
		<section class="search">
			<h3 class="search__title">Создание скрипта для прописки RET на {{ bs }}</h3>
			{% if result == "FAIL" %}
			<p class="duty__text">Скрипт для {{ bs }} не создан! Не выбрано ни одного UniqueID для прописки! </p>
			{% else %}
			<p class="duty__text">Скрипт для {{ bs }} успешно создан!</p>
			<h3 class="ret__title">Прописать RET на {{ bs }}:</h3>
			<form action="{% url 'set_ret' %}" method="POST">
				{% csrf_token %}
				<p>
				    <label for="id_bs">Номер сетевого элемента:</label>
				    <input type="text" name="bs" value="{{ bs }}" maxlength="9" required="" id="id_bs">
				</p>
				<p>
				    <label for="id_login">Имя пользователя ESC:</label>
				    <input type="text" name="login" maxlength="15" required="" id="id_login">
				</p>
				<p>
				    <label for="id_password">Пароль пользователя ESC:</label>
				    <input type="text" name="password" maxlength="15" required="" id="id_password">
				</p>
				<p>
				    <label for="id_server">Сервер ESC:</label>
				    <select name="server" id="id_server">
				    	<option value="ESC01">ESC01</option>
				    	<option value="ESC02">ESC02</option>
				    	<option value="ESC03">ESC03</option>
				    	<option value="ESC04">ESC04</option>
				    	<option value="ESC05">ESC05</option>
				    	<option value="ESC06">ESC06</option>
				    	<option value="ESC07">ESC07</option>
				    	<option value="ESC08">ESC08</option>
				    	<option value="ESC09">ESC09</option>
				    </select>
				</p>
				<input class="site__comments-button" type="submit" name="submit" value="Прописать" />
			</form>
			{% endif %}
		</section>
	</div>
</main>
{% endblock %}

simplyret/templates/simplyret/index.html
{% extends "layout/basic_ret.html" %}
{% block content %}
<main class="page-main">
	<div class="hero_container">
		<section class="search">
			<h3 class="ret__title">Сделать выгрузку Unique ID</h3>
			<form action="{% url 'upload_unique_id' %}" method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<input class="site__comments-button" type="submit" name="submit" value="Выгрузить" />
			</form>
		</section>
		<section class="search">
			<h3 class="ret__title">Проверить калибровку RET</h3>
			<form action="{% url 'check_calibration' %}" method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<input class="site__comments-button" type="submit" name="submit" value="Проверить" />
			</form>
		</section>
	</div>
</main>
{% endblock %}

simplyret/templates/simplyret/set-ret.html
{% extends "layout/basic_ret.html" %}
{% block title %}
{{ bs }} прописка RET
{% endblock %}
{% block content %}
<main class="page-main">
	<div class="hero_container">
		<section class="search">
			<h3 class="search__title">Статус прописки RET на {{ bs }}</h3>
			<p class="search__disclaimer">БС: {{ bs }}</p>
			<p class="search__disclaimer">Имя пользователя: {{ login }}</p>
			<p class="search__disclaimer">Сервер: {{ server }}</p> 
			<h3 class="ret__title"> {{ result }}</h3>
		</section>
	</div>
</main>
{% endblock %}

simplyret/templates/simplyret/upload-current.html
{% extends "layout/basic_ret.html" %}
{% block title %}
{{ bs }} текущая выгрузка
{% endblock %}
{% block content %}
<main class="page-main">
	<div class="hero_container">
		<section class="search">
			<h3 class="search__title">Проверка наличия текущей выгрузки</h3>
			<p class="search__disclaimer">БС: {{ bs }}</p>
			{% if RET_list == "Nothing" %}
			<p class="duty__text">Выгрузка по элементу {{ bs }} отсутствует!</p>
			{% elif RET_list == "Empty_file" %}
			<p class="duty__text">{{ bs }} - RET не подключены! Проверьте подключение RET!</p>
			{% else %}   
			<form action="{% url 'create_script' %}" method="POST">
				{% csrf_token %}
			    <table class="ret__table">
				    <tr>
					    <th class="ret__table-title">№</th>
					    <th class="ret__table-title">BS</th>
					    <th class="ret__table-title">Sector</th>
					    <th class="ret__table-title">RRU</th>
					    <th class="ret__table-title">Unique ID</th>
                        <th class="ret__table-title">Technology</th>
					    <th class="ret__table-title">Current El Tilt</th>					
				    </tr>
			        {% for ret in RET_list %}
			        {% if ret.2 == 1 %}
			        <tr>
				        <td class="ret__table-cell ret__table-cell--sec1">{{ ret.0 }}</td>				
				        <td class="ret__table-cell ret__table-cell--sec1">{{ ret.1 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec1">{{ ret.2 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec1">{{ ret.3 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec1">{{ ret.4 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec1">
                            <select size="1" name="tech_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="GSM900">GSM900</option>
                                <option value="GSM1800">GSM1800</option>
                                <option value="UMTS2100">UMTS2100</option>
                                <option value="UMTS2100(6x)">UMTS2100(6x)</option>
                                <option value="LTE800">LTE800</option>
                                <option value="LTE1800">LTE1800</option>
                                <option value="LTE1800(2)">LTE1800(2)</option>
                                <option value="LTE2100">LTE2100</option>
                                <option value="LTE2100(6x)">LTE2100(6x)</option>
                                <option value="LTE2300">LTE2300</option>
                                <option value="LTE2300(2)">LTE2300(2)</option>
                                <option value="LTE2600">LTE2600</option>
                                <option value="LTE2600(2)">LTE2600(2)</option>                        
                            </select></td>                    
				        <td class="ret__table-cell ret__table-cell--sec1">
                            <select size="1" name="tilt_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100">100</option>
                                <option value="110">110</option>
                                <option value="120">120</option>
                            </select></td>
			        </tr>
			        {% elif ret.2 == 2 %}
			        <tr>
						<td class="ret__table-cell ret__table-cell--sec2">{{ ret.0 }}</td>				
				        <td class="ret__table-cell ret__table-cell--sec2">{{ ret.1 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec2">{{ ret.2 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec2">{{ ret.3 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec2">{{ ret.4 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec2">
                            <select size="1" name="tech_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="GSM900">GSM900</option>
                                <option value="GSM1800">GSM1800</option>
                                <option value="UMTS2100">UMTS2100</option>
                                <option value="UMTS2100(6x)">UMTS2100(6x)</option>
                                <option value="LTE800">LTE800</option>
                                <option value="LTE1800">LTE1800</option>
                                <option value="LTE1800(2)">LTE1800(2)</option>
                                <option value="LTE2100">LTE2100</option>
                                <option value="LTE2100(6x)">LTE2100(6x)</option>
                                <option value="LTE2300">LTE2300</option>
                                <option value="LTE2300(2)">LTE2300(2)</option>
                                <option value="LTE2600">LTE2600</option>
                                <option value="LTE2600(2)">LTE2600(2)</option>                        
                            </select></td>				
				        <td class="ret__table-cell ret__table-cell--sec2">
                            <select size="1" name="tilt_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100">100</option>
                                <option value="110">110</option>
                                <option value="120">120</option>
                            </select></td>
			        </tr>
			        {% else %}
			        <tr class="sites__table-row">
				        <td class="ret__table-cell ret__table-cell--sec3">{{ ret.0 }}</td>				
				        <td class="ret__table-cell ret__table-cell--sec3">{{ ret.1 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec3">{{ ret.2 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec3">{{ ret.3 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec3">{{ ret.4 }}</td>
				        <td class="ret__table-cell ret__table-cell--sec3">
                            <select size="1" name="tech_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="GSM900">GSM900</option>
                                <option value="GSM1800">GSM1800</option>
                                <option value="UMTS2100">UMTS2100</option>
                                <option value="UMTS2100(6x)">UMTS2100(6x)</option>
                                <option value="LTE800">LTE800</option>
                                <option value="LTE1800">LTE1800</option>
                                <option value="LTE1800(2)">LTE1800(2)</option>
                                <option value="LTE2100">LTE2100</option>
                                <option value="LTE2100(6x)">LTE2100(6x)</option>
                                <option value="LTE2300">LTE2300</option>
                                <option value="LTE2300(2)">LTE2300(2)</option>
                                <option value="LTE2600">LTE2600</option>
                                <option value="LTE2600(2)">LTE2600(2)</option>                        
                            </select></td>				
				        <td class="ret__table-cell ret__table-cell--sec3">
                            <select size="1" name="tilt_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100">100</option>
                                <option value="110">110</option>
                                <option value="120">120</option>
                            </select></td>
			        </tr>
			        {% endif %}
			        {% endfor %}
		        </table>	
				<input type="text" name="bs" value="{{ bs }}" hidden>
                <input class="site__comments-button" type="submit" name="submit" value="Сгенерировать скрипт" />
			</form>
			{% endif %}
		</section>
	</div>
</main>
{% endblock %}

simplyret/templates/simplyret/upload-unique-id.html
{% extends "layout/basic_ret.html" %}
{% block title %}
{{ bs }} выгрузка UniqueID
{% endblock %}
{% block content %}
<main class="page-main">
	<div class="hero_container">
		<section class="search">
			<h3 class="search__title">Выгрузка UniqueID на {{ bs }}</h3>
			<p class="search__disclaimer">БС: {{ bs }}</p>
			<p class="search__disclaimer">Имя пользователя: {{ login }}</p>
			<p class="search__disclaimer">Сервер: {{ server }}</p>            
			{% if RET_list == "No_connection" %}
			<p class="duty__text">Сетевой элемент {{ bs }} недоступен или не существует!</p>
			{% elif RET_list == "No_auth" %}
			<p class="duty__text">Нет подключения! Проверьте имя/пароль пользователя ESC!</p>
            {% elif RET_list == "Empty_file" %}
			<p class="duty__text">{{ bs }} - RET не подключены! Проверьте подключение RET!</p>
			{% else %}      
            <form action="{% url 'create_script' %}" method="POST"> 
                {% csrf_token %} 
			    <table class="ret__table">
			    	<tr>
					    <th class="ret__table-title">№</th>
					    <th class="ret__table-title">BS</th>
					    <th class="ret__table-title">Sector</th>
					    <th class="ret__table-title">RRU</th>
					    <th class="ret__table-title">Unique ID</th>
                        <th class="ret__table-title">Technology</th>
					    <th class="ret__table-title">Current El Tilt</th>					
			    	</tr>
			        {% for ret in RET_list %}
			        {% if ret.2 == 1 %}
			        <tr>
			        	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.0 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.1 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.2 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.3 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec1">{{ ret.4 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec1">
                            <select size="1" name="tech_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="GSM900">GSM900</option>
                                <option value="GSM1800">GSM1800</option>
                                <option value="UMTS2100">UMTS2100</option>
                                <option value="UMTS2100(6x)">UMTS2100(6x)</option>
                                <option value="LTE800">LTE800</option>
                                <option value="LTE1800">LTE1800</option>
                                <option value="LTE1800(2)">LTE1800(2)</option>
                                <option value="LTE2100">LTE2100</option>
                                <option value="LTE2100(6x)">LTE2100(6x)</option>
                                <option value="LTE2300">LTE2300</option>
                                <option value="LTE2300(2)">LTE2300(2)</option> 
                                <option value="LTE2600">LTE2600</option>
                                <option value="LTE2600(2)">LTE2600(2)</option>                        
                            </select></td>                    
			        	<td class="ret__table-cell ret__table-cell--sec1">
                            <select size="1" name="tilt_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100">100</option>
                                <option value="110">110</option>
                                <option value="120">120</option>
                            </select></td>
			        </tr>
			        {% elif ret.2 == 2 %}
			        <tr>
			        	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.0 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.1 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.2 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.3 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec2">{{ ret.4 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec2">
                            <select size="1" name="tech_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="GSM900">GSM900</option>
                                <option value="GSM1800">GSM1800</option>
                                <option value="UMTS2100">UMTS2100</option>
                                <option value="UMTS2100(6x)">UMTS2100(6x)</option>
                                <option value="LTE800">LTE800</option>
                                <option value="LTE1800">LTE1800</option>
                                <option value="LTE1800(2)">LTE1800(2)</option>
                                <option value="LTE2100">LTE2100</option>
                                <option value="LTE2100(6x)">LTE2100(6x)</option>
                                <option value="LTE2300">LTE2300</option>
                                <option value="LTE2300(2)">LTE2300(2)</option>
                                <option value="LTE2600">LTE2600</option>
                                <option value="LTE2600(2)">LTE2600(2)</option>                        
                        </select></td>				
			        	<td class="ret__table-cell ret__table-cell--sec2">
                            <select size="1" name="tilt_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100">100</option>
                                <option value="110">110</option>
                                <option value="120">120</option>
                            </select>
                        </td>
			        </tr>
			        {% else %}
			        <tr class="sites__table-row">
			        	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.0 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.1 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.2 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.3 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec3">{{ ret.4 }}</td>
			        	<td class="ret__table-cell ret__table-cell--sec3">
                            <select size="1" name="tech_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="GSM900">GSM900</option>
                                <option value="GSM1800">GSM1800</option>
                                <option value="UMTS2100">UMTS2100</option>
                                <option value="UMTS2100(6x)">UMTS2100(6x)</option>
                                <option value="LTE800">LTE800</option>
                                <option value="LTE1800">LTE1800</option>
                                <option value="LTE1800(2)">LTE1800(2)</option>
                                <option value="LTE2100">LTE2100</option>
                                <option value="LTE2100(6x)">LTE2100(6x)</option>
                                <option value="LTE2300">LTE2300</option>
                                <option value="LTE2300(2)">LTE2300(2)</option>
                                <option value="LTE2600">LTE2600</option>
                                <option value="LTE2600(2)">LTE2600(2)</option>                        
                        </select></td>				
			        	<td class="ret__table-cell ret__table-cell--sec3">
                            <select size="1" name="tilt_{{ ret.0 }}">
                                <option value="Not Used">Not Used</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100">100</option>
                                <option value="110">110</option>
                                <option value="120">120</option>
                            </select>
                        </td>
			        </tr>
			        {% endif %}
			        {% endfor %}
		        </table>			
                <input type="text" name="bs" value="{{ bs }}" hidden>
				<input class="site__comments-button" type="submit" name="submit" value="Сгенерировать скрипт" />
			</form>
            {% endif %}            
		</section>
	</div>
</main>
{% endblock %}