simplytechdb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('simplyret/', include('simplyret.urls')),
    path('techdb/', include('techdb.urls')),
    path('', RedirectView.as_view(url='/techdb/', permanent=True))
]

techdb/urls.py
from django.urls import path, include

from .views import index, by_category, phonebook, site_view, new_site, SearchResultsView, bss_info, tn_info, shedule, \
    useful_sites, new_site_info

urlpatterns = [
    path('tn_info/', tn_info, name='tn_info'),
    path('bss_info/', bss_info, name='bss_info'),
    path('phonebook/', phonebook, name='phonebook'),
    path('useful_sites/', useful_sites, name='useful_sites'),
    path('shedule/', shedule, name='shedule'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path("site/<int:site_id>/", site_view, name="site_view"),
    path('new_info/', new_site_info, name='new_site_info'),
    path('new/', new_site, name='new'),
    path('<int:category_id>/', by_category, name='by_category'),
    path('', index, name='index'),
]

techdb/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=30, db_index=True, verbose_name='Наименование')

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'
        ordering = ['name']

    def __str__(self):
        return self.name


class Site(models.Model):
    title = models.CharField(max_length=50, verbose_name='Сайт')
    category = models.ForeignKey('Category', null=True, on_delete=models.PROTECT, verbose_name='Категория')
    address = models.TextField(null=True, blank=True, verbose_name='Адрес')
    status = models.TextField(null=True, blank=True, verbose_name='Статус')
    alternative = models.TextField(null=True, blank=True, verbose_name='Альтернатива')

    class Meta:
        verbose_name_plural = 'Сайты'
        verbose_name = 'Сайт'
        ordering = ['title']

    def __str__(self):
        return self.title


class Comment(models.Model):
    site = models.ForeignKey(Site, related_name='comment', on_delete=models.PROTECT, verbose_name='Сайт')
    author = models.CharField(max_length=80, verbose_name='Автор')
    text = models.TextField(verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    active = models.BooleanField(default=True, verbose_name='Активный')

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['created']

    def __str__(self):
        return 'Comment by {} on {}'.format(self.author, self.text)


class SiteCommon(models.Model):
    title = models.OneToOneField(Site, on_delete=models.PROTECT, max_length=50, verbose_name='Сайт')
    distance = models.IntegerField(null=True, blank=True, verbose_name='Расстояние')
    priority = models.TextField(null=True, blank=True, verbose_name='Приоритет')
    type_hardware = models.TextField(null=True, blank=True, verbose_name='Тип аппаратной')

    class Meta:
        verbose_name_plural = 'Сайты_общая'
        verbose_name = 'Сайт'
        ordering = ['title']

    def __str__(self):
        return str(self.title)


class SiteBatteries(models.Model):
    title = models.OneToOneField(Site, on_delete=models.PROTECT, max_length=50, verbose_name='Сайт')
    system_of_voltage = models.TextField(null=True, blank=True, verbose_name='Система питания')
    num_of_rect = models.IntegerField(null=True, blank=True, verbose_name='Количество выпрямителей')
    battery_type = models.TextField(null=True, blank=True, verbose_name='Тип АКБ')
    battery_num = models.IntegerField(null=True, blank=True, verbose_name='Количество АКБ')
    battery_cap = models.IntegerField(null=True, blank=True, verbose_name='Емкость АКБ')
    battery_date = models.DateField(null=True, blank=True, verbose_name='Дата установки АКБ')

    class Meta:
        verbose_name_plural = 'Сайты_АКБ'
        verbose_name = 'Сайт'
        ordering = ['title']

    def __str__(self):
        return str(self.title)


class SiteEquipment(models.Model):
    title = models.ForeignKey(Site, on_delete=models.PROTECT, max_length=50, verbose_name='Сайт')
    device = models.TextField(null=True, blank=True, verbose_name='Оборудование')
    serial_number = models.TextField(null=True, blank=True, verbose_name='Серийный номер')

    class Meta:
        verbose_name_plural = 'Сайты_оборудование'
        verbose_name = 'Сайт'
        ordering = ['device']

    def __str__(self):
        return str(self.title)


class SiteRRL(models.Model):
    title = models.ForeignKey(Site, on_delete=models.PROTECT, max_length=50, verbose_name='Сайт')
    radiolink = models.TextField(null=True, blank=True, verbose_name='Направление РРЛ')
    type_rrl = models.TextField(null=True, blank=True, verbose_name='Тип оборудования')
    ip_access = models.TextField(null=True, blank=True, verbose_name='IP адрес')

    class Meta:
        verbose_name_plural = 'Сайты_РРЛ'
        verbose_name = 'Сайт'
        ordering = ['radiolink']

    def __str__(self):
        return str(self.title)


class SiteEnergy(models.Model):
    title = models.ForeignKey(Site, on_delete=models.PROTECT, max_length=50, verbose_name='Сайт')
    energy = models.TextField(null=True, blank=True, verbose_name='Электропитание')

    class Meta:
        verbose_name_plural = 'Сайты_Электропитание'
        verbose_name = 'Сайт'
        ordering = ['title']

    def __str__(self):
        return str(self.title)


class SiteOldInfo(models.Model):
    title = models.ForeignKey(Site, on_delete=models.PROTECT, max_length=50, verbose_name='Сайт')
    old_info = models.TextField(null=True, blank=True, verbose_name='Информация')

    class Meta:
        verbose_name_plural = 'Сайты_Старая_информация'
        verbose_name = 'Сайт'
        ordering = ['title']

    def __str__(self):
        return str(self.title)


class SiteQuazar(models.Model):
    title = models.ForeignKey(Site, on_delete=models.PROTECT, max_length=50, verbose_name='Сайт')
    location = models.TextField(null=True, blank=True, verbose_name='Локация')
    access = models.TextField(null=True, blank=True, verbose_name='Доступ')
    keys = models.TextField(null=True, blank=True, verbose_name='Ключи')
    energy = models.TextField(null=True, blank=True, verbose_name='Электроснабжение')
    other = models.TextField(null=True, blank=True, verbose_name='Прочее')

    class Meta:
        verbose_name_plural = 'Сайты_Квазар'
        verbose_name = 'Сайт'
        ordering = ['title']

    def __str__(self):
        return str(self.title)


class PhoneBook(models.Model):
    title = models.CharField(max_length=70, verbose_name='Район')
    phone = models.TextField(null=True, blank=True, verbose_name='Телефон')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий')

    class Meta:
        verbose_name_plural = 'Телефоны сетей'
        verbose_name = 'телефон'
        ordering = ['title']

    def __str__(self):
        return self.title


class DutyShedule(models.Model):
    date = models.DateTimeField(auto_now_add=False, verbose_name='Дата дежурства')
    duty = models.TextField(null=True, blank=True, verbose_name='Дежурный')
    duty_add = models.TextField(null=True, blank=True, verbose_name='Группа дежурного')
    support = models.TextField(null=True, blank=True, verbose_name='Поддержка')
    support_add = models.TextField(null=True, blank=True, verbose_name='Группа поддержки')

    class Meta:
        verbose_name_plural = 'Дежурные'
        verbose_name = 'дежурный'
        ordering = ['date']

    def __str__(self):
        return self.date


class DutyTimetable(models.Model):
    date_start = models.DateTimeField(auto_now_add=False, verbose_name='Дата начала дежурства')
    date_end = models.DateTimeField(auto_now_add=False, verbose_name='Дата окончания дежурства')
    duty = models.TextField(null=True, blank=True, verbose_name='Дежурный')
    duty_add = models.TextField(null=True, blank=True, verbose_name='Группа дежурного')
    support = models.TextField(null=True, blank=True, verbose_name='Поддержка')
    support_add = models.TextField(null=True, blank=True, verbose_name='Группа поддержки')

    class Meta:
        verbose_name_plural = 'Дежурные'
        verbose_name = 'дежурный'
        ordering = ['date_start']

    def __str__(self):
        return self.date_start

techdb/forms.py
from django.forms import ModelForm

from .models import Site, Comment, SiteCommon, SiteBatteries


class SiteForm(ModelForm):
    class Meta:
        model = Site
        fields = ('title', 'address', 'status', 'alternative', 'category')


class SiteCommonForm(ModelForm):
    class Meta:
        model = SiteCommon
        fields = ('title', 'distance', 'priority', 'type_hardware')


class SiteAkbForm(ModelForm):
    class Meta:
        model = SiteBatteries
        fields = ('title', 'system_of_voltage', 'num_of_rect', 'battery_type', 'battery_num', 'battery_cap',
                  'battery_date')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

techdb/views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
import datetime

from .models import (Site, Category, SiteCommon, SiteEquipment, SiteBatteries, SiteRRL, SiteEnergy, SiteOldInfo,
                     SiteQuazar, PhoneBook, DutyTimetable)
from .forms import SiteForm, CommentForm, SiteAkbForm, SiteCommonForm


def index(request):
    sites = Site.objects.all()
    paginator = Paginator(sites, 10)
    page_num = request.GET.get('page')
    page = paginator.get_page(page_num)
    all_dutys = DutyTimetable.objects.all()
    now_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    for i in all_dutys:
        if str(i.date_start) < str(now_date) and str(i.date_end) > str(now_date):
            today_duty = i
    return render(request, 'techdb/index.html', {'page': page, 'today_duty': today_duty})


def by_category(request, category_id):
    sites = Site.objects.filter(category=category_id)
    categories = Category.objects.all()
    current_category = Category.objects.get(pk=category_id)
    context = {'sites': sites, 'categories': categories, 'current_category': current_category}
    return render(request, 'techdb/by_category.html', context)


def site_view(request, site_id):
    site = get_object_or_404(Site, id=site_id)
    site_common = SiteCommon.objects.get(title_id=site_id)
    site_equipment = SiteEquipment.objects.filter(title_id=site_id)
    site_rrl = SiteRRL.objects.filter(title_id=site_id)
    site_energy = SiteEnergy.objects.filter(title_id=site_id)
    site_old_info = SiteOldInfo.objects.filter(title_id=site_id)
    site_batteries = SiteBatteries.objects.get(title_id=site_id)
    site_quazar = SiteQuazar.objects.filter(title_id=site_id)
    comments = site.comment.filter(active=True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.site = site
            new_comment.author = request.user.get_full_name()
            new_comment.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()
    return render(request, "techdb/site.html", {'site': site, 'site_common': site_common,
                                                'site_equipment': site_equipment,
                                                'site_batteries': site_batteries,
                                                'site_rrl': site_rrl,
                                                'site_energy': site_energy,
                                                'site_old_info': site_old_info,
                                                'comments': comments,
                                                'comment_form': comment_form,
                                                'site_quazar': site_quazar})


class SearchResultsView(ListView):
    model = Site
    template_name = 'techdb/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Site.objects.filter(
            Q(title__icontains=query) | Q(address__icontains=query)
        )
        return object_list


@login_required
def new_site(request):
    form = SiteForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'techdb/new.html', {'form': form})
    new_site = form.save(commit=False)
    new_site.save()
    return redirect('new_site_info')

@login_required
def new_site_info(request):
    form_common = SiteCommonForm(request.POST or None)
    form_akb = SiteAkbForm(request.POST or None)
    site = Site.objects.latest('id')
    if not form_common.is_valid() or not form_akb.is_valid():
        return render(request, 'techdb/new_info.html', {'form_akb': form_akb, 'form_common': form_common, 'site': site})
    new_site_common = form_common.save(commit=False)
    new_site_common.save()
    new_site_akb = form_akb.save(commit=False)
    new_site_akb.save()
    return redirect('index')


def bss_info(request):
    return render(request, 'techdb/bss_info.html')
    

def tn_info(request):
    return render(request, 'techdb/tn_info.html')


def phonebook(request):
    phones = PhoneBook.objects.all()
    return render(request, 'techdb/phonebook.html', {'phones': phones})


def useful_sites(request):
    return render(request, 'techdb/useful_sites.html')


def shedule(request):
    now_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    dutys = DutyTimetable.objects.filter(date_start__gt=str(now_date))    
    dutys_past = DutyTimetable.objects.filter(date_start__lt=str(now_date))[74:]
    # duty_today = DutyTimetable.objects.filter(date_start__lt=str(now_date), date_end__gt=str(now_date))
    return render(request, 'techdb/shedule.html', {'dutys': dutys, 'dutys_past': dutys_past})
    

techdb/templates/techdb/bss_info.html
{% extends "layout/basic.html" %}
{% block title %}
Справочник BSS
{% endblock %}
{% block content %}
<main class="page-main">
	<h2 class="info__title">Справочник BSS</h2>
	<section class="info__chapter">
		<h3 class="info__subtitle">Базовые команды для Baseband</h3>

		<dl class="info__text">
			<h4 class="info__subject">Статус основных элементов</h4>
			<dt class="info__label">Проверка RRU и секторов: </dt>
			<dd class="info__command">st rru<br>
				st cell
			</dd>
			<dt class="info__label">Проверка GSM: </dt>
			<dd class="info__command">lst gsm<br>
				st trx
			</dd>
			<dt class="info__label">Проверка КСВ, оптики температуры на портах и проч.: </dt>
			<dd class="info__command">invxr</dd>
			<dt class="info__label">Проверка доступности RNC: </dt>
			<dd class="info__command">lst iub</dd>
			<dt class="info__label">Проверка доступности MME LTE: </dt>
			<dd class="info__command">st mme</dd>
			<dt class="info__label">Проверка синхронизации: </dt>
			<dd class="info__command">sts <br>
				st ntp</dd>
			<dt class="info__label">Проверка GPS: </dt>
			<dd class="info__command">gpsstatus</dd>
			<dt class="info__label">Проверка RET: </dt>
			<dd class="info__command">st ret<br>
				hget AntennaNearUnit operationalState|^uniqueId|serialNumber|productNumber|rfPortRef<br>
				hget RetSubUnit= calibrationStatus|electricalAntennaTilt|tiltChangeStatus|operationalState</dd>
			<dt class="info__label">Проверка внешних аварий:</dt>
			<dd class="info__command">st alarmport <br>
				hget Alarmport
				operationalState|administrativeState|alarmSlogan|normallyOpen|perceivedSeverity|activeExternalAlarm
			</dd>
			<h4 class="info__subject">Секторная информация</h4>
			<dt class="info__label">Привязка к несущим: </dt>
			<dd class="info__command">st sector <br>
				get sector ref<br>
				get sector reserv
			</dd>
			<dt class="info__label">Проверка rfBranch:</dt>
			<dd class="info__command">st carr<br>
				get carr ref<br>
				get carr reserv
			</dd>
			<dt class="info__label">Проверка количества прописанных TRX: </dt>
			<dd class="info__command">hget carr [tr]xant</dd>
			<dt class="info__label">Проверка мощности на секторах: </dt>
			<dd class="info__command">get sector power$ <br>
			</dd>
			<h4 class="info__subject">Информация по RRU/Radio</h4>
			<dt class="info__label">Общая информация по RRU: </dt>
			<dd class="info__command">st rru <br>
				hget rru prod
			</dd>
			<dt class="info__label">Привязка антенных выходов к RRU: </dt>
			<dd class="info__command">hget RfBranch ref<br>
				hget RfBranch reserve
			</dd>
			<dt class="info__label">Подключение RRU (sfp->riport->rilink): </dt>
			<dd class="info__command">st sfp<br>
				st riport<br>
				st rilink<br>
				hget RiLink rate|ref|st
			</dd>
			<h4 class="info__subject">Транспорт</h4>
			<dt class="info__label">Проверка прописанных vlan: </dt>
			<dd class="info__command">get port vlan<br>
				get vlanport= reserv
			</dd>
			<dt class="info__label">Проверка прописанных ip-адресов: </dt>
			<dd class="info__command">lst router<br>
				lpr router<br>
				lget router address<br>
				get AddressIPv4 res
			</dd>
			<dt class="info__label">Проверка доступности IUB (ping defaultRouter IUB): </dt>
			<dd class="info__command">mcc router=iub ping XX.XX.XX.XX</dd>
			
		</dl>
		<h3 class="info__subtitle">Базовые команды для DUW</h3>
		<dl class="info__text">
			<dt class="info__label">Рестарт DUW: </dt>
			<dd class="info__command">acc managedelement=1 manualrestart </dd>
			<dt class="info__label">Рестарт RRU (указать сектор в параметре SectorAntenna):
			<dt>
			<dd class="info__command">acc SectorAntenna=1-1,AuxPlugInUnit=RRUW-1 restartAuxUnit </dd>
		</dl>
		<h3 class="info__subtitle">Базовые команды для TCU</h3>
		<dl class="info__text">
			<dt class="info__label">Общая информация по интерфейсам на TCU:</dt>
			<dd class="info__command">showtable interface </dd>
			<dt class="info__label">Проверка аварий:</dt>
			<dd class="info__command">getalarmlist </dd>
			<dt class="info__label">Проверка температуры :</dt>
			<dd class="info__command">gettemperature</dd>
			<dt class="info__label">Справочная информация: </dt>
			<dd class="info__command">help</dd>
		</dl>
	</section>
</main>
{% endblock %}

techdb/templates/techdb/by_category.html
{% extends "layout/basic.html" %}
{% block title %} {{ current_category.name }} {% endblock %}
{% block content %}
<h2 class="section-title">Список сайтов</h2>
<h3 class="section-title">Категория: {{ current_category.name }}</h3>
<div class="about-content">
	<form>
		<p><input type="search" name="q" placeholder="Поиск сайта">
			<input type="submit" value="Найти"></p>
	</form>
	<table>
		<tr>
			<th>Сайт</th>
			<th>Категория</th>
			<th>Адрес</th>
			<th>Статус</th>
			<th>Альтернатива</th>
		</tr>
		{% for site in sites %}
		<tr>
			<td><a href="{% url 'site_view' site.id %}">{{ site.title }}</a></td>
			<td><a href="{% url 'by_category' site.category.pk %}">{{ site.category.name }}</a></td>
			<td>{{ site.address }}</td>
			<td>{{ site.status}}</td>
			<td>{{ site.alternative }}</td>
		</tr>
		{% endfor %}
	</table>
</div>
{% endblock %}

techdb/templates/techdb/index.html
{% extends "layout/basic.html" %}
{% block content %}
<main class="page-main">
	<div class="hero_container">
		<section class="search">
			<h3 class="search__title">Поиск сайта</h3>
			<form action="{% url 'search_results' %}" method="get">
				<input class="search__input" name="q" type="text" placeholder="Например AA0001...">
			</form>
			<p class="search__disclaimer">*Поиск работает по номеру сайта, в т.ч. без индекса региона, и по адресу с
				учетом регистра</p>
		</section>
		<section class="duty">
			<h4 class="duty_date">{% now "d E Y" %}</h4>
			<h5 class="duty_title">Дежурный инженер:</h5>
			<p class="duty_text">{{ today_duty.duty}}<span class="duty_add-info">{{ today_duty.duty_add}}</span></p>
			<h5 class="duty_title">Инженер поддержки:</h5>
			<p class="duty_text">{{ today_duty.support}}<span class="duty_add-info">{{ today_duty.support_add}}</span>
			</p>
			<a href="{% url 'shedule' %}" class="duty__link">График дежурств</a>
		</section>
	</div>
	<section class="sites">
		<h3 class="sites__title site__title--main">Список сайтов
			<i class="arrow down"></i>
		</h3>
		<div class="rollup-container-sites visually-hidden">
			<table class="sites__table">
				<tr>
					<th class="sites__table-title">Сайт</th>
					<th class="sites__table-title">Категория</th>
					<th class="sites__table-title">Адрес</th>
					<th class="sites__table-title">Статус</th>
					<th class="sites__table-title">Альтернатива</th>
				</tr>
				{% for site in page %}
				<tr>
					<td class="sites__table-cell">
						<a href="{% url 'site_view' site.id %}" class="sites__link">{{ site.title }}</a>
					</td>
					<td class="sites__table-cell">{{ site.category.name }}</td>
					<td class="sites__table-cell">{{ site.address }}</td>
					<td class="sites__table-cell">{{ site.status}}</td>
					{% if site.alternative != None %}
					<td class="sites__table-cell">{{ site.alternative }}</td>
					{% else %}
					<td></td>
					{% endif %}
				</tr>
				{% endfor %}
			</table>
			{% include "techdb/paginator.html" %}
		</div>
	</section>

</main>
{% endblock %}

techdb/templates/techdb/new.html
{% extends "layout/basic.html" %}
{% block title %} Добавить сайт {% endblock %}
{% block content %}

<div class="login__container">
    <h2 class="login__title">Добавить новый сайт</h2>
    <p>
    <form method="post">
        {% csrf_token %}
        <p><label for="id_title">Сайт:</label> <input type="text" name="title" maxlength="50" required id="id_title">
        </p>
        <p><label for="id_address">Адрес:</label> <textarea name="address" cols="40" rows="1" id="id_address">
</textarea></p>
        <p><label for="id_status">Статус:</label> <textarea name="status" cols="40" rows="1" id="id_status">
</textarea></p>
        <p><label for="id_alternative">Альтернатива:</label> <textarea name="alternative" cols="40" rows="1"
                id="id_alternative">
</textarea></p>
        <p><label for="id_category">Категория:</label> <select name="category" required id="id_category">

                <option value="1" selected>Базовая станция</option>

                <option value="2">Транспортная точка</option>

                <option value="3">Шестиризация</option>

            </select></p>
        <input class="site__comments-button" type="submit" value="Добавить" />
    </form>
    </p>
</div>
{% endblock %}

techdb/templates/techdb/new_info.html
{% extends "layout/basic.html" %}
{% block title %} Добавить сайт (инфо) {% endblock %}
{% block content %}

<div class="login__container">
    <h2 class="login__title">Добавить информацию по новому сайту {{ site.title }}</h2>
    <p>
    <form method="post">
        {% csrf_token %}
        <h3 class="site__title--not-main">Общая информация</h3>
        <input id="id_title" type="text" name="title" value="{{ site.id }}" hidden>
        <p>
            <label for="id_distance">Расстояние:</label> 
            <input type="number" name="distance" id="id_distance">
        </p>
        <p>
            <label for="id_priority">Приоритет:</label> 
            <textarea name="priority" cols="40" rows="1" id="id_priority">
            </textarea>
        </p>
        <p>
            <label for="id_type_hardware">Тип аппаратной:</label> 
            <textarea name="type_hardware" cols="40" rows="1" id="id_type_hardware">
            </textarea>
        </p>
        <h3 class="site__title--not-main">Аккумуляторы и ИБП</h3>
        <input id="id_title" type="text" name="title" value="{{ site.id }}" hidden>
        <p>
            <label for="id_system_of_voltage">Система питания:</label>
            <textarea name="system_of_voltage" cols="40" rows="1" id="id_system_of_voltage">
            </textarea>
        </p>
        <p>
            <label for="id_num_of_rect">Количество выпрямителей:</label>
            <input type="number" name="num_of_rect" id="id_num_of_rect">
        </p>
        <p>
            <label for="id_battery_type">Тип АКБ:</label>
            <textarea name="battery_type" cols="40" rows="1" id="id_battery_type">
            </textarea>
        </p>
        <p>
            <label for="id_battery_num">Количество АКБ:</label>
            <input type="number" name="battery_num" id="id_battery_num" placeholder="Количество полок">
        </p>
        <p>
            <label for="id_battery_cap">Емкость АКБ:</label>
            <input type="number" name="battery_cap" id="id_battery_cap">
        </p>
        <p>
            <label for="id_battery_date">Дата установки АКБ:</label>
            <input type="date" name="battery_date" id="id_battery_date">
        </p>

        <input class="site__comments-button" type="submit" value="Добавить">
    </form>
    </p>
</div>
{% endblock %}

techdb/templates/techdb/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav class="pagination__nav">
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

techdb/templates/techdb/phonebook.html
{% extends "layout/basic.html" %}
{% block title %}
Телефонный справочник
{% endblock %}
{% block content %}
<main class="page-main">
    <h2 class="phonebook__title">Телефонный справочник</h2>
    <section class="phonebook">        
        <h3 class="phonebook__subtitle">Телефоны электрических сетей</h3>
        <table class="sites__table phonebook__table">
            <tr>
                <th class="sites__table-title">Район</th>
                <th class="sites__table-title">Телефон</th>
                <th class="sites__table-title">Примечание</th>
            </tr>
            {% for phone in phones %}
            <tr>
                <td class="sites__table-cell">{{ phone.title }}</td>
                <td class="sites__table-cell">{{ phone.phone }}</td>
                <td class="sites__table-cell">{{ phone.comment}}</td>
            </tr>
            {% endfor %}
        </table>
    </section>
</main>
{% endblock %}

techdb/templates/techdb/tn_info.html
{% extends "layout/basic.html" %}
{% block title %}
Справочник TN
{% endblock %}
{% block content %}
<main class="page-main">
	<h2 class="section-title">Справочник TN</h2>
	<div class="about-content">
		<p>Здесь будет создан справочник по TN</p>
	</div>
</main>
{% endblock %}